import sys
import os
import math
import numpy as np

#
#--- SET THE KP TOLERANCE VARIABLE.  IF THE KP VALUE FOR WHICH OUTPUT
#--- IS DESIRED CHANGES BY MORE THAN THIS VALUE, THE KP SCALING
#--- PARAMETERS ARE RECALCULATED
#
XKPTOL  = 0.3
#
#--- GLOBAL VARIABLES
#
BLENDX1 = -8.0      #--- XGSM (XTAIL) LIMIT FOR *NOT* USING Z-LAYERS (IF XTAIL >= BLENDX1, NO Z-LAYERS USED)
BLENDX2 = -10.0     #--- XGSM (XTAIL) LIMIT FOR *ONLY* USING Z-LAYERS (IF XTAIL >= BLENDX1, NO Z-LAYERS USED)
MAXCELL = 1000      #--- MAXIMUM NUMBER OF NEAR-NEIGHBOR CELLS USED IN CALCULATING THE AVERAGE FLUX AT THIS LOCATION
MAXKP   = 9         #--- NUMBER OF KP BINS IN THE DATA FILE
MAXNSPHVOL = 100000 #--- MAXIMUM NUMBER OF SUB-VOLUME ELEMENTS STORES IN THE STREAMLINE MAPPING SEARCH VOLUME
MAXNUM  = 65        #--- MAXIMUM NUMBER OF VOLUME ELEMENTS ALONG AN AXIS USED IN DATAFILE
MAXPNT  = 250000    #--- MAXIMUM NUMBER OF POINTS USED IN DATAFILE
NSAVE   = 10        #--- THE NUMBER OF RANGE SORTED DATA CELLS TO SAVE BEFORE REMOVING THE HIGHEST & LOWEST FLUX VALUES
NUMSEC  = 10        #--- NUMBER OF SPATILA SECTORS: MAX NUSED IN MAGNETOSPHERE, MAGNETOSHEATH, OR SOLAR WIND
PI      = 3.14159265359
XINC    = 1.0       #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: LENGTH OF VOLUME ELEMENT IN X-DIRECTION (RE)
YINC    = 1.0       #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: LENGTH OF VOLUME ELEMENT IN Y-DIRECTION (RE)
ZINC    = 1.0       #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: LENGTH OF VOLUME ELEMENT IN Z-DIRECTION (RE
XMIN    = -30.0     #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: MINIMUM X-VALUE OF VOLUME ELEMENT (RE)
YMIN    = -30.0     #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: MINIMUM Y-VALUE OF VOLUME ELEMENT (RE)
ZMIN    = -30.0     #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: MINIMUM Z-VALUE OF VOLUME ELEMENT (RE)
XMAX    = +30.0     #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: MAXIMUM X-VALUE OF VOLUME ELEMENT (RE)
YMAX    = +30.0     #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: MAXIMUM Y-VALUE OF VOLUME ELEMENT (RE)
ZMAX    = +30.0     #--- CHANDRA VOLUME ELEMENT DATABASE PARAMETERS: MAXIMUM Z-VALUE OF VOLUME ELEMENT (RE)
NUM2    = 6         #--- SUB-VOLUME ELEMENT DATABASE PARAMETERS: NUMBER OF SUB-VOLUME ELEMENTS IN EACH DIRECTION
XINC2   = 0.1666666 #--- SUB-VOLUME ELEMENT DATABASE PARAMETERS: LENGTH OF SUB-VOLUME ELEMENT IN X-DIRECTION (RE)
YINC2   = 0.1666666 #--- SUB-VOLUME ELEMENT DATABASE PARAMETERS: LENGTH OF SUB-VOLUME ELEMENT IN Y-DIRECTION (RE)
ZINC2   = 1.0       #--- SUB-VOLUME ELEMENT DATABASE PARAMETERS: LENGTH OF SUB-VOLUME ELEMENT IN Z-DIRECTION (RE)